#+TITLE:     Will Henney's emacs configuration
#+AUTHOR:    William Henney
#+EMAIL:     will@henney.org
#+DATE:      2011-11-04 Fri
#+DESCRIPTION:
#+KEYWORDS: emacs
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:


* Introduction 
  :LOGBOOK:
  CLOCK: [2011-11-04 Fri 23:18]--[2011-11-04 Fri 23:26] =>  0:08
  :END:
This is my personal emacs configuration setup. All the various =.el= files are tangled from this org-mode file. 

** How to use the themes
   :LOGBOOK:
   CLOCK: [2011-11-06 Sun 13:40]
   :END:
+ Currently the "Custom Themes" setting is broken in that "Save Theme Settings" only saves the last theme selected, erasing all the others. 
+ To work around that, it is necessary to directly customize the variable =custom-enabled-themes= to include the list of themes to enable. For example, I currently have the following line in my =custom.el=: 
#+begin_src elisp
   '(custom-enabled-themes (quote (wjh-org-faces wombat wjh-org-misc wjh-redbox-cursor)))
#+end_src
+ Another annoying thing is that somewhere Aquamacs sets =default-frame-alist= to have black text on a white background. So it is necessary to customize that variable to remove the =foreground-color= and =background-color= items from the alist.  Still, this seems fixed now. 


* Custom themes
  :LOGBOOK:
  CLOCK: [2011-11-04 Fri 23:26]--[2011-11-05 Sat 00:05] =>  0:39
  CLOCK: [2011-11-04 Fri 22:18]--[2011-11-04 Fri 23:18] =>  1:00
  :END:

I am currently using the =wombat= theme, which has a nice dark gray background. These are some additional modular themes, which combine nicely with =wombat=. At least that is the idea. They will probably also work well with any other theme that has a dark background. 


** Template

A theme called FOO is defined in a file =FOO-theme.el=, which has the following structure: 
#+begin_src elisp
  (deftheme FOO
    "Comment about theme FOO")
  (custom-theme-set-variables
   'FOO
   '(SYMBOL (EXPRESSION))
   ...
   )
  (custom-theme-set-faces
   'FOO
   '(FACE (SPEC))
   ...
   )
  (provide-theme 'FOO)
#+end_src

I should really make a Yasnippet snippet out of this. 

** Org faces
   :LOGBOOK:
   CLOCK: [2011-11-05 Sat 20:48]--[2011-11-05 Sat 21:18] =>  0:30
   :END:
   :PROPERTIES:
   :tangle:   wjh-org-faces-theme.el
   :END:

The main thing that we do here is to make the faces for tables and source blocks inherit from =fixed-pitch=. This is especially necessary if you change the default text font to be varible pitch. There are advantages to this, even if you use a fixed pitch default font. In my case, I use monaco as the default, but =fixed-pitch= is set to courier, which looks more "code-y" and helps set off the source blocks. 


#+begin_src elisp
  (deftheme wjh-org-faces
    "Created 2011-11-04.")
  (custom-theme-set-faces
   'wjh-org-faces
   '(org-block ((t (:inherit (shadow fixed-pitch)))))
   '(org-block-background ((t (:inherit fixed-pitch))))
   '(org-code ((t (:inherit (shadow fixed-pitch)))))
   '(org-table ((default (:inherit fixed-pitch))
                (((class color) (background light)) (:foreground "Blue4"))))
   '(org-date ((((class color) (background light)) (:foreground "Purple4" :underline t))))
   '(org-document-title ((default  (:weight bold))
                         (((class color) (background light)) 
                          (:foreground "midnight blue"))
                         (((class color) (background dark)) 
                          (:foreground "white"))
                         ))
   ;; '(org-level-5 ((t (:inherit outline-5 :foreground "#c06d1a"))))
   ;; '(org-level-6 ((t (:inherit outline-6 :foreground "#317563"))))
   '(org-link ((((class color) (background light)) (:foreground "gray50" :underline t :weight bold))))
   '(org-todo ((t (:foreground "#b93030" :weight bold))))
  
   ;; Org column
   '(org-column-title ((((class color) (min-colors 16) (background light)) (:background "grey90" :underline t :weight bold :family "monaco"))))
   )
  (provide-theme 'wjh-org-faces)
#+end_src


** Redbox cursor
   :PROPERTIES:
   :tangle:   wjh-redbox-cursor-theme.el
   :END:
Use a nice red hollow box for the cursor. This is a good compromise between visibility and not getting in the way. Strangely, it is the background color that needs to be set to red (I use =OrangeRed1=). The foreground colour seems to have no effect. 

In non-selected windows, I use a horizontal bar instead. 

#+begin_src elisp
  (deftheme wjh-redbox-cursor
    "Created 2011-11-04.")
  (custom-theme-set-variables
   'wjh-redbox-cursor
   '(blink-cursor-mode nil)
   '(cursor-type (quote hollow))
   '(cursor-in-non-selected-windows (quote hbar))
   )
  (custom-theme-set-faces
   'wjh-redbox-cursor
   '(cursor ((t (:background "OrangeRed1" :foreground "#f6f3e8"))))
   )
  (provide-theme 'wjh-redbox-cursor)
  
#+end_src

** Org misc
   :LOGBOOK:
   - Note taken on [2011-11-06 Sun 14:03] \\
     This is now working fine.
   CLOCK: [2011-11-05 Sat 21:21]--[2011-11-05 Sat 21:35] =>  0:14
   - Note taken on [2011-11-05 Sat 21:22] \\
     Trying to get timestamps to go into LOGBOOK drawer.  Why is this not working?
   :END:
   :PROPERTIES:
   :tangle:   wjh-org-misc-theme.el
   :END:

#+begin_src elisp
  (deftheme wjh-org-misc
    "Miscellaneous tweaks to org-mode configuration")
  (custom-theme-set-variables
   'wjh-org-misc
   '(org-disputed-keys (quote (([(control tab)] . [(control shift tab)]))))
   '(org-emphasis-alist (quote (("*" bold "<b>" "</b>") ("/" italic "<i>" "</i>") ("_" underline "<span style=\"text-decoration:underline;\">" "</span>") ("=" org-code "<code>" "</code>" verbatim) ("~" org-verbatim "<code>" "</code>" verbatim) ("@" org-warning "<b>" "</b>"))))
   '(org-enforce-todo-dependencies t)
   '(org-export-latex-packages-alist (quote (("" "siunitx" t))))
   '(org-log-into-drawer t)
   '(org-replace-disputed-keys t)
   )
  (provide-theme 'wjh-org-misc)
#+end_src

* Packages
** Org mode
