
(deftheme wjh-org-faces
  "Created 2011-11-04.")
(custom-theme-set-faces
 'wjh-org-faces
 '(org-block ((t (:inherit (shadow fixed-pitch) :height 0.8))))
 '(org-block-background ((default (:inherit fixed-pitch) :height 0.8)
                         (((class color) (background dark)) (:background "gray18"))
                         ) nil "This looks good with zenburn. YMMV otherwise")
 '(org-code ((t (:inherit (shadow fixed-pitch)))))
 '(org-formula (
                (((class color) (background dark)) (:foreground "LightSalmon1"))
                ))
 '(org-table ((default (:inherit fixed-pitch :height 0.7))
              (((class color) (background light)) (:foreground "Blue4"))
              (((class color) (background dark)) (:foreground "PaleTurquoise1"))
              ))
 '(org-date ((default (:underline t))
             (((class color) (background light)) (:foreground "Purple4"))
             (((class color) (background dark)) (:foreground "#c2a9c2"))
             ))
 '(org-document-title ((default  (:weight bold))
                       (((class color) (background light)) 
                        (:foreground "midnight blue"))
                       (((class color) (background dark)) 
                        (:foreground "white"))
                       ))
 '(org-formula ((t (:inherit org-table :foreground "chocolate1"))))
 '(org-meta-line ((t (:inherit font-lock-comment-face :slant italic))))
 '(org-special-keyword ((t (:inherit font-lock-keyword-face :slant italic))))
 ;; LemonChiffon to GhostWhite
 '(org-level-1 ((((class color) (background dark)) (:foreground "#fffacd"))))
 '(org-level-2 ((((class color) (background dark)) (:foreground "#fefad4"))))
 '(org-level-3 ((((class color) (background dark)) (:foreground "#fdf9db"))))
 '(org-level-4 ((((class color) (background dark)) (:foreground "#fcf9e2"))))
 '(org-level-5 ((((class color) (background dark)) (:foreground "#fbf9ea"))))
 '(org-level-6 ((((class color) (background dark)) (:foreground "#faf9f1"))))
 '(org-level-7 ((((class color) (background dark)) (:foreground "#f9f8f8"))))
 '(org-level-8 ((((class color) (background dark)) (:foreground "#f8f8ff"))))
 '(org-link ((((class color) (background light)) (:foreground "gray50" :underline t :weight bold))))
 '(org-todo ((t (:weight bold)))
            (((class color) (background light)) (:foreground "#b93030"))
            (((class color) (background dark)) (:foreground "DarkOrange"))
            )

 ;; Org column
 '(org-column-title ((((class color) (min-colors 16) (background light)) (:background "grey90" :underline t :weight bold :family "monaco"))))

 '(outline-1 ((t (:weight bold))))
 '(outline-2 ((t (:inherit outline-1)))) 
 '(outline-3 ((t (:inherit outline-1)))) 
 '(outline-4 ((t (:inherit outline-1)))) 
 '(outline-5 ((t (:inherit outline-1)))) 
 '(outline-6 ((t (:inherit outline-1)))) 
 '(outline-7 ((t (:inherit outline-1)))) 
 '(outline-8 ((t (:inherit outline-1)))) 
 )
(provide-theme 'wjh-org-faces)
